version: '3'
services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d/'
    ports:
      - 80:80
  web:
    build: .
    command: [ "uvicorn", "main.py", "--port", "8000", "--reload" ]
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1



