version: '3'
services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - './docker/nginx:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d/'
    ports:
      - 80:80
  web:
    build: ./docker/fastapi
    ports:
      - 8000:8000
